#!/bin/sh

# Modificaciones basadas en 
# http://geekytheory.com/actualiza-y-limpia-tu-linux-con-una-sola-orden/
# En general, no me gusta la opción -y así que la dejo como opción
# In general, I don't like to use -y, so I'll let the user decide
#
# Usaremos aptitude en lugar de apt
# We will use aptitude instead of apt

YES=$1

# Si la opción no es -y, la borramos
# If the option is not -y, we delete it.

if [ "$1" != "-y" ] ;
then
	YES=""
fi

sudo aptitude update $YES && echo "" && \
sudo aptitude safe-upgrade $YES&& echo "" && \
sudo localepurge && echo "" && \
sudo deborphan | xargs sudo apt-get remove $YES --purge && echo "" && \
sudo aptitude autoclean $YES && echo "" && \
sudo aptitude moo
