#!/bin/sh

# Modificaciones basadas en 
# http://geekytheory.com/actualiza-y-limpia-tu-linux-con-una-sola-orden/
# En general, no me gusta la opción -y así que la dejo como opción
# In general, I don't like to use -y, so I'll let the user decide
#

YES=$1

# Si la opción no es -y, la borramos
# If the option is not -y, we delete it.

if [ "$1" != "-y" ] ;
then
	YES=""
fi

sudo apt-get update $YES && echo "" && \
sudo apt-get safe-upgrade $YES || sudo apt-get upgrade $YES && echo "" && \
sudo apt-get dselect-upgrade && \
sudo apt-get autoremove $YES && echo "" && \
sudo localepurge || echo "localepurge not available" && echo "" && \
sudo deborphan | xargs sudo dpkg --purge $YES && echo "" && \
sudo apt-get autoclean $YES && echo "" 
sudo /usr/lib/update-notifier/update-motd-updates-available --force
sudo /usr/lib/update-notifier/update-motd-reboot-required --force
sudo apt-get moo

